name: Release

on:
  push:
    tags: '*'

permissions:
  contents: write
  id-token: write
  attestations: write
  artifact-metadata: write

jobs:
  release:
    runs-on: ubuntu-slim

    steps:
      - name: Checkout
        uses: actions/checkout@v6.0.2

      - name: Zip Files
        run: |
          mkdir ProtectSurrendered
          cp README.md mod.txt ProtectSurrendered/
          cp -r hooks ProtectSurrendered/
          zip -r ProtectSurrendered@${{ github.ref_name }}.zip ProtectSurrendered

      - uses: actions/attest@v4
        with:
          subject-path: ProtectSurrendered@${{ github.ref_name }}.zip

      - name: Create Release
        uses: ncipollo/release-action@v1.20.0
        with:
          artifacts: ProtectSurrendered@${{ github.ref_name }}.zip
